[package]
name = "gravity-v2"
version = "0.1.0"
authors = ["Mikail <mikail.khan45@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.5.1"
legion = "0.1.1"

gfx_core = "0.9"
gfx_device_gl = "0.16"
imgui = "0.2.0"
imgui-gfx-renderer = "0.2.0"

[profile.dev]
debug=0
